// <auto-generated>
// Written by tools/readme-media/figures.mjs from its figures/*.mjs, beside the PNGs it writes to
// wwwroot/figures: each figure's size, what it shows, and the names its numbers stand for. Draw the
// figures again rather than edit this file (ADR-0110).
// </auto-generated>

namespace ExGrid.Docs.Figures;

internal static class DrawnFigures
{
    internal static readonly IReadOnlyDictionary<string, DrawnFigure> ByName = new Dictionary<string, DrawnFigure>
    {
        ["grid-anatomy"] = new(
            "grid-anatomy", 778, 524,
            "An ExGrid of positions under Header Groups, panned past its Pinned Columns, with two rows marked and a range selected; each part the list names is ringed and numbered",
            [
                new("Pinned Column", "held at the edge while the others pan under it"),
                new("Header Group", "a label over adjacent columns"),
                new("Mark Column", "its ticks are Row Marks, which your application holds"),
                new("Row Stripe", "on every second row of the result"),
                new("Selection", "rectangles of cells, by position"),
                new("Focus", "the active cell, which typing enters"),
                new("Extent", "the end that moves as the range grows"),
                new("Overflow", "a number too wide shows ####, never a shorter number"),
                new("Selection Summary", "Excel's status-bar figures over the Selection"),
            ]),
        ["pivot-anatomy"] = new(
            "pivot-anatomy", 790, 702,
            "An ExPivot report of 2025's sales by region and country, with Europe open, beside its PivotTable Fields pane; each part the list names is ringed and numbered",
            [
                new("Report filter", "a field in Filters"),
                new("Value Field", "Revenue, with its Aggregation, Sum"),
                new("Header Group", "a column Item over its columns"),
                new("Group row", "an outer Item, heading its Items"),
                new("Item", "one value of a field in Rows"),
                new("Subtotal", "of the group, at its foot"),
                new("Grand total", "of everything the report counts"),
                new("Cell", "one per combination of Items, computed from its Leaf Aggregate"),
                new("Areas", "Filters, Columns, Rows and Values"),
            ]),
        ["sheet-anatomy"] = new(
            "sheet-anatomy", 936, 560,
            "An ExSheet expenses claim beside last quarter's, with the total's Formula open in the Cell Editor; each part the list names is ringed and numbered",
            [
                new("Sheet Toolbar", "opt-in buttons that act on the Selection"),
                new("Name Box", "where the Focus is"),
                new("Formula Bar", "the Focus cell's Entry, editable here too"),
                new("Headings", "column letters and row numbers"),
                new("Cell Editor", "the uncommitted text, over its cell"),
                new("Reference Outline", "the cells a Reference in the Formula names"),
                new("Number Format", "turns a Value into the text shown, here 0.0%"),
                new("Error Value", "an error, carried as data; here a division by nothing"),
                new("Value", "what a cell's Entry evaluates to"),
            ]),
    };
}
