using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace ExGrid.Docs.Generator;

/// <summary>
/// The Docs Site's build step (ADR-0110). Two inputs reach it as additional files:
/// <list type="bullet">
/// <item>every <c>.razor</c>, <c>.cs</c>, <c>.html</c> and <c>.sh</c> under the site's <c>Examples/</c> folder, which it
/// emits as <c>ExampleSources</c>: each file's text and its highlighted HTML;</item>
/// <item>the shipped assemblies' XML documentation files, which it emits as <c>ApiDocs</c>: each
/// member's summary as HTML, keyed by its documentation id.</item>
/// </list>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DocsGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var projectDir = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
            options.GlobalOptions.TryGetValue("build_property.MSBuildProjectDirectory", out var dir) ? dir : "");

        var examples = context.AdditionalTextsProvider
            .Combine(projectDir)
            .Select((pair, cancel) =>
            {
                var (file, dir) = pair;
                var relative = Relative(dir, file.Path);
                if (relative is null || !relative.StartsWith("Examples/", StringComparison.Ordinal))
                    return null;
                var extension = Path.GetExtension(relative);
                if (extension is not (".razor" or ".cs" or ".html" or ".sh"))
                    return null;
                var text = file.GetText(cancel)?.ToString().Replace("\r\n", "\n") ?? "";
                var html = extension switch
                {
                    ".razor" or ".html" => Highlighter.Razor(text),
                    ".cs" => Highlighter.CSharp(text),
                    _ => Highlighter.Shell(text),
                };
                return new Example(relative, extension.Substring(1), text, html);
            })
            .Where(example => example is not null)
            .Collect();

        // The decision records' file names, so a summary's "ADR-0016" links to the record.
        var adrs = context.AdditionalTextsProvider
            .Select((file, _) => Path.GetFileName(file.Path))
            .Where(name => AdrFile.IsMatch(name))
            .Collect()
            .Select((names, _) => names.ToImmutableDictionary(n => n.Substring(0, 4), n => n));

        var docs = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".xml", StringComparison.OrdinalIgnoreCase))
            .Combine(adrs)
            .Select((pair, cancel) => Summaries(pair.Left.GetText(cancel)?.ToString() ?? "", pair.Right))
            .Collect();

        context.RegisterSourceOutput(examples, (spc, all) => spc.AddSource("ExampleSources.g.cs", EmitExamples(all!)));
        // Only what a Consumer can reach: the documentation files also describe internal members.
        var publicDocs = docs.Combine(context.CompilationProvider).Select((pair, _) =>
        {
            var (files, compilation) = pair;
            return files.Select(file => file.Where(entry => IsPublic(entry.Key, compilation)).ToImmutableArray()).ToImmutableArray();
        });

        context.RegisterSourceOutput(publicDocs, (spc, all) => spc.AddSource("ApiDocs.g.cs", EmitDocs(all)));
    }

    // Whether the member a documentation id names is visible outside its assembly.
    private static bool IsPublic(string id, Compilation compilation)
    {
        var symbol = DocumentationCommentId.GetFirstSymbolForDeclarationId(id, compilation);
        for (var s = symbol; s is not null and not INamespaceSymbol; s = s.ContainingSymbol)
        {
            if (s.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal))
                return false;
        }
        return symbol is not null;
    }

    private sealed record Example(string Path, string Language, string Text, string Html);

    private static string? Relative(string dir, string path)
    {
        if (dir.Length == 0)
            return null;
        var full = path.Replace('\\', '/');
        var root = dir.Replace('\\', '/').TrimEnd('/') + "/";
        return full.StartsWith(root, StringComparison.Ordinal) ? full.Substring(root.Length) : null;
    }

    private static SourceText EmitExamples(ImmutableArray<Example> all)
    {
        var code = new StringBuilder();
        code.AppendLine("// <auto-generated/> by ExGrid.Docs.Generator from the files under Examples/ (ADR-0110).");
        code.AppendLine("namespace ExGrid.Docs;");
        code.AppendLine("internal static partial class ExampleSources");
        code.AppendLine("{");
        code.AppendLine("    private static readonly global::System.Collections.Generic.Dictionary<string, ExampleSource> All = Build();");
        code.AppendLine("    private static global::System.Collections.Generic.Dictionary<string, ExampleSource> Build() => new()");
        code.AppendLine("    {");
        foreach (var example in all.OrderBy(e => e.Path, StringComparer.Ordinal))
        {
            code.Append("        [").Append(Literal(example.Path)).Append("] = new(")
                .Append(Literal(example.Path)).Append(", ")
                .Append(Literal(example.Language)).Append(", ")
                .Append(Literal(example.Text)).Append(", ")
                .Append(Literal(example.Html)).AppendLine("),");
        }
        code.AppendLine("    };");
        code.AppendLine("}");
        return SourceText.From(code.ToString(), Encoding.UTF8);
    }

    private static SourceText EmitDocs(ImmutableArray<ImmutableArray<KeyValuePair<string, string>>> files)
    {
        var code = new StringBuilder();
        code.AppendLine("// <auto-generated/> by ExGrid.Docs.Generator from the shipped assemblies' XML documentation (ADR-0110).");
        code.AppendLine("namespace ExGrid.Docs;");
        code.AppendLine("internal static partial class ApiDocs");
        code.AppendLine("{");
        code.AppendLine("    private static readonly global::System.Collections.Generic.Dictionary<string, string> Summaries = Build();");
        code.AppendLine("    private static global::System.Collections.Generic.Dictionary<string, string> Build() => new()");
        code.AppendLine("    {");
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var entry in files.SelectMany(f => f).OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            if (seen.Add(entry.Key))
                code.Append("        [").Append(Literal(entry.Key)).Append("] = ").Append(Literal(entry.Value)).AppendLine(",");
        }
        code.AppendLine("    };");
        code.AppendLine("}");
        return SourceText.From(code.ToString(), Encoding.UTF8);
    }

    private static string Literal(string text) => SymbolDisplay.FormatLiteral(text, quote: true);

    // Each member's summary, as HTML. A file that is not a documentation file yields nothing.
    private static readonly Regex AdrFile = new(@"^\d{4}-.+\.md$", RegexOptions.Compiled);
    private static readonly Regex AdrMention = new(@"\bADR-(\d{4})\b", RegexOptions.Compiled);

    // "ADR-0016" as a link to the record on GitHub, where the build knows its file.
    private static string LinkAdrs(string html, ImmutableDictionary<string, string> adrs) =>
        AdrMention.Replace(html, m => adrs.TryGetValue(m.Groups[1].Value, out var file)
            ? "<a href=\"https://github.com/AkiraMisawa/ex-grid/blob/main/docs/adr/" + file + "\" target=\"_blank\" rel=\"noopener\">" + m.Value + "</a>"
            : m.Value);

    private static ImmutableArray<KeyValuePair<string, string>> Summaries(string xml, ImmutableDictionary<string, string> adrs)
    {
        if (xml.Length == 0)
            return ImmutableArray<KeyValuePair<string, string>>.Empty;
        XDocument document;
        try
        {
            document = XDocument.Parse(xml, LoadOptions.PreserveWhitespace);
        }
        catch (System.Xml.XmlException)
        {
            return ImmutableArray<KeyValuePair<string, string>>.Empty;
        }
        var members = document.Root?.Element("members");
        if (document.Root?.Name != "doc" || members is null)
            return ImmutableArray<KeyValuePair<string, string>>.Empty;
        var result = ImmutableArray.CreateBuilder<KeyValuePair<string, string>>();
        foreach (var member in members.Elements("member"))
        {
            var id = (string?)member.Attribute("name");
            var summary = member.Element("summary");
            if (id is null || summary is null)
                continue;
            var html = new StringBuilder();
            Render(summary, html);
            result.Add(new KeyValuePair<string, string>(id, LinkAdrs(Collapse(html.ToString()), adrs)));
        }
        return result.ToImmutable();
    }

    private static readonly Regex Spaces = new(@"\s+", RegexOptions.Compiled);

    private static string Collapse(string html) => Spaces.Replace(html, " ").Trim();

    private static void Render(XElement element, StringBuilder html)
    {
        foreach (var node in element.Nodes())
        {
            switch (node)
            {
                case XText text:
                    Highlighter.Text(html, text.Value);
                    break;
                case XElement child:
                    switch (child.Name.LocalName)
                    {
                        case "c":
                            html.Append("<code>");
                            Highlighter.Text(html, child.Value);
                            html.Append("</code>");
                            break;
                        case "see":
                        case "seealso":
                            html.Append("<code>");
                            Highlighter.Text(html, Reference(child));
                            html.Append("</code>");
                            break;
                        case "paramref":
                        case "typeparamref":
                            html.Append("<code>");
                            Highlighter.Text(html, (string?)child.Attribute("name") ?? "");
                            html.Append("</code>");
                            break;
                        case "para":
                            html.Append(" <br /> ");
                            Render(child, html);
                            break;
                        case "list":
                            html.Append("<ul>");
                            foreach (var item in child.Elements("item"))
                            {
                                html.Append("<li>");
                                Render(item, html);
                                html.Append("</li>");
                            }
                            html.Append("</ul>");
                            break;
                        default:
                            Render(child, html);
                            break;
                    }
                    break;
            }
        }
    }

    // What a <see> names, as a reader would write it: the member's own name, its type's for a
    // constructor, the keyword for a langword, or the element's text.
    private static string Reference(XElement see)
    {
        if (!string.IsNullOrWhiteSpace(see.Value))
            return see.Value;
        if ((string?)see.Attribute("langword") is { } word)
            return word;
        var cref = (string?)see.Attribute("cref") ?? (string?)see.Attribute("href") ?? "";
        var colon = cref.IndexOf(':');
        if (colon == 1)
            cref = cref.Substring(2);
        var paren = cref.IndexOf('(');
        if (paren >= 0)
            cref = cref.Substring(0, paren);
        var parts = cref.Split('.');
        var name = parts[parts.Length - 1];
        if (name == "#ctor" && parts.Length > 1)
            name = parts[parts.Length - 2];
        var tick = name.IndexOf('`');
        return tick >= 0 ? name.Substring(0, tick) : name;
    }
}
