// Writes the per-glyph tables the estimate charges letters and currency signs by (ADR-0016; ticket
// 83), from the records beside this file:
//   src/ExGrid/Columns/DefaultGlyphWidths.cs  the core's, at 14px and at 12px;
//   src/ExGrid.MudBlazor/RobotoGlyphTable.cs  ExGrid.MudBlazor's, at 14px, which the core scales.
// Run it after measure.mjs: node tests/GlyphWidths/tables.mjs
//
// A glyph joins a table only where every record shows the face drawing it itself. A glyph the face
// lacks is painted in a fallback the platform chooses, so it is left to the other class.
// - The core's: a glyph DejaVu Sans draws, which is what Linux paints for system-ui. Its width is the
//   widest any core record shows: macOS's system-ui stack, fallback included, and DejaVu Sans.
// - Roboto's: a glyph Roboto draws, at the wider of its 14px width and its 12px one scaled to 14.
// Each width is the widest at 400, 500 and 600 (regular) or at 700 (bold), a shade over.
import fs from 'node:fs';
import path from 'node:path';
import { classed } from './classes.mjs';

const here = path.dirname(new URL(import.meta.url).pathname);
const repo = path.resolve(here, '..', '..');
const records = (face) => fs.readdirSync(here)
  .filter((f) => f.startsWith(`${face}.`) && f.endsWith('.json'))
  .map((f) => JSON.parse(fs.readFileSync(path.join(here, f), 'utf8')));
const regular = [400, 500, 600];
const bold = [700];
const shade = (px) => Math.ceil((px + 0.005) * 100) / 100;
const eligible = (g) => /[\p{L}\p{Sc}]/u.test(g) && !classed.includes(g);
const width = (r, g, size, weights) => {
  const i = r.glyphs.indexOf(g);
  if (i < 0) throw new Error(`${r.face} (${r.platform}) has no reading for '${g}'.`);
  return Math.max(...weights.map((w) => r.sizes[size].glyphs[w][i] / 64));
};
const drawsItself = (r, g, family) => {
  const i = r.glyphs.indexOf(g);
  return i >= 0 && [...regular, ...bold].every((w) => r.painters[w][i] === family);
};

const core = [...records('system-ui'), ...records('dejavu-sans')];
const dejavu = records('dejavu-sans');
const roboto = records('roboto');
if (core.length < 2 || dejavu.length === 0 || roboto.length === 0) throw new Error('Measure the three faces first.');

const glyphsOf = (rs) => [...new Set(rs.flatMap((r) => r.glyphs))].filter(eligible)
  .sort((a, b) => a.codePointAt(0) - b.codePointAt(0));
const coreGlyphs = glyphsOf(core).filter((g) => dejavu.every((r) => drawsItself(r, g, 'DejaVu Sans')));
const coreAt = (size) => coreGlyphs.map((g) => [g,
  shade(Math.max(...core.map((r) => width(r, g, size, regular)))),
  shade(Math.max(...core.map((r) => width(r, g, size, bold))))]);
const robotoGlyphs = glyphsOf(roboto).filter((g) => roboto.every((r) => drawsItself(r, g, 'Roboto')));
const robotoAt14 = robotoGlyphs.map((g) => [g, ...[regular, bold].map((ws) =>
  shade(Math.max(...roboto.flatMap((r) => [width(r, g, '14', ws), width(r, g, '12', ws) * 14 / 12]))))]);

const measuredBy = (rs) => [...new Set(rs.map((r) => `${r.face} on ${r.platform} (${r.measured})`))].join(', ');
const entries = (rows) => rows.map(([g, r, b]) => `        (${JSON.stringify(g)}, ${r.toFixed(2)}, ${b.toFixed(2)}),`).join('\n');
const table = (name, size, rows, summary) => `    /// <summary>${summary}</summary>
    public static GlyphWidthTable ${name} { get; } = new(${size},
    [
${entries(rows)}
    ]);`;
const header = (rs) => `// Generated by tests/GlyphWidths/tables.mjs from ${measuredBy(rs)}.
// Do not edit by hand: measure again and run it (tests/GlyphWidths/README.md).`;

fs.writeFileSync(path.join(repo, 'src/ExGrid/Columns/DefaultGlyphWidths.cs'), `${header(core)}

namespace ExGrid.Columns;

/// <summary>
/// The core's per-glyph widths (ADR-0016; ticket 83): each letter and currency sign DejaVu Sans
/// draws, at the widest of DejaVu Sans and macOS's <c>system-ui</c>, so a date's month or a
/// currency symbol is charged what it paints rather than the other class. Regular is the widest at
/// 400, 500 and 600, bold at 700, a shade over.
/// </summary>
internal static class DefaultGlyphWidths
{
${table('At14', 14, coreAt('14'), 'At 14px: Compact, Standard and Comfortable.')}

${table('At12', 12, coreAt('12'), 'At 12px, measured there rather than scaled: Excel.')}
}
`);
fs.writeFileSync(path.join(repo, 'src/ExGrid.MudBlazor/RobotoGlyphTable.cs'), `${header(roboto)}

using ExGrid.Columns;

namespace ExGrid.MudBlazor;

/// <summary>
/// Roboto's per-glyph widths (ADR-0016; ticket 83): each letter and currency sign Roboto draws, at
/// 14px, covering its 12px width scaled to 14 too, since the core scales the table to the resolved
/// font size. Regular is the widest at 400, 500 and 600, bold at 700, a shade over.
/// </summary>
internal static class RobotoGlyphTable
{
${table('At14', 14, robotoAt14, 'At 14px, which the core scales to the resolved size.')}
}
`);
console.log(`core: ${coreGlyphs.length} glyphs; Roboto: ${robotoGlyphs.length} glyphs`);
